# Generated by Django 2.1 on 2019-01-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
