# Generated by Django 2.1 on 2019-02-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
