# Generated by Django 2.1 on 2019-02-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='from_user_hide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='to_user_hide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
