# Generated by Django 2.1 on 2019-02-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='coversation',
        ),
    ]
