# Generated by Django 2.1 on 2019-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190218_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='from_user_hide',
            field=models.CharField(blank=True, default='show', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='to_user_hide',
            field=models.CharField(blank=True, default='show', max_length=70, null=True),
        ),
    ]
