# Generated by Django 2.1 on 2019-02-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_coversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='chat.Message'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
