# Generated by Django 2.1 on 2019-02-13 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
